on:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  push-jscodeshift:
    runs-on: ubuntu-latest
    steps:
      - name: Show latest jscodeshift version
        uses: actions/setup-node@v2
          with:
            node-version: '16'
            cache: npm
        run: npm show jscodeshift version
