on:
  schedule:
    - cron:  '24 23 * * *'
  workflow_dispatch:
jobs:
  push-jscodeshift:
    runs-on: ubuntu-latest
    steps:
      - name: Show latest jscodeshift version
        run: npm show jscodeshift version
