on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
jobs:
  push-jscodeshift:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest jscodeshift version
        id: get_latest_jscodeshift_version
        run: echo "::set-output name=latest_jscodeshift_version::$(npm show jscodeshift version)"
      - name: Print latest jscodeshift version
        run: echo "{{steps.get_latest_jscodeshift_version.outputs.latest_jscodeshift_version}}"
